export default {
  TOGGLE_ALERTING: 1,
  TOGGLE_GO_OFFLINE_REASONS: 2,
  SELECT_CITY: 3,
  ADD_GO_OFFLINE_REASON: 4,
  TOGGLE_GO_OFFLINE_REASON_VISIBILITY: 5,
  TOGGLE_CONFIRMATION_DIALOG: 6,
  HANDLE_ALERTING_INPUT: 7,
  HANDLE_GO_OFFLINE_REASON_INPUT: 8,
  TOGGLE_SAVE_BUTTON: 9,
  UPDATE_CITY_SETTINGS: 10,
  UPDATE_GO_OFFLINE_REASON_ORDER: 11,
  UPDATE_GO_OFFLINE_REASONS: 12,
  TOGGLE_DRIVER_PERFORMANCE: 13
};
